@startuml
title Diagrama de Estados - Pasajero

[*] --> PlanificaViaje : Selecciona ruta y horario
PlanificaViaje --> SeDirigeALaParada : Camina hacia la parada
SeDirigeALaParada --> EsperaEnParada : Llega a la parada
EsperaEnParada --> SubeAlBus : Llega el bus y aborda

SubeAlBus --> PagaTarifa : Valida la tarjeta o paga en efectivo
PagaTarifa --> ViajaEnBus : Busca asiento o espacio disponible
ViajaEnBus --> SaleEnParadaDeseada : Llega a la parada deseada y desciende

SaleEnParadaDeseada --> [*] : Finaliza el viaje
SaleEnParadaDeseada --> PlanificaViaje : Inicia planificación de un nuevo viaje

@enduml
